vich_uploader:
    db_driver: orm

    mappings:
        articles_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        slider_image:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true